[package]
name = "lolcow-fortune"
version = "0.1.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "lolcow-fortune"
path = "src/main.rs"
required-features = ["build-binary"]

[features]
default = ["build-binary"]
build-binary = [
    "attohttpc",
    "lcowsay",
    "directories",
    "flate2",
    "lcat",
    "structopt",
    "tar",
]

[dependencies]
# Lib
memchr = "2.3"
rand = { version = "0.7", features = ["std", "small_rng"] }

# Binary
directories = { version = "2.0.2", optional = true }
structopt =  { version = "0.3.14", optional = true }

# Download
flate2 = { version = "1.0", optional = true, default-features = false, features = ["rust_backend"] }
attohttpc = { version = "0.13", optional = true, default-features = false, features = ["tls"] }
tar = { version = "0.4", optional = true }

[dependencies.lcowsay]
git = "https://github.com/davidkna/lcowsay-rs"
optional = true

[dependencies.lcat]
git = "https://github.com/davidkna/lcat-rs"
optional = true